<a href="https://colab.research.google.com/github/Finix-07/pytorch_practice/blob/main/pytorch_tuts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


## Intro to tensors

### Creating tensors


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim #gives dimensions

0

In [4]:
# working with vectors
#
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape


torch.Size([2])

In [7]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[0]

tensor([7, 8])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR



tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape # 1 3x3 tensor

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Working with random Tensors.

Why random tensors?

Random tensors are imp because many neural networks learn is that they start with tensors full of random numbers and adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers

In [14]:
# Creates a random tensor of size(3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3474, 0.3320, 0.1898, 0.6086],
        [0.6193, 0.7154, 0.4189, 0.2136],
        [0.3608, 0.6267, 0.8009, 0.9660]])

In [15]:
random_tensor.ndim

2

In [16]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [17]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [21]:
# use torch.range(), if error use arange

one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Creating tensors like
# making a tensor like the input tensor

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

**Note:** Tensor datatypes is a one of the 3 big errors you'll run into with PyTorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [23]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # What datatype is the tensor(eg float32 or float16)
                               device = None, # What device is your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor # multiplies the 2 tensors

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors

1. Tensors not right datatype - To do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`


In [30]:
# lets see the implementation

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0415, 0.4933, 0.3969, 0.6134],
        [0.7917, 0.4260, 0.8662, 0.9843],
        [0.4736, 0.1407, 0.3010, 0.7988]])

In [31]:
# Finding the details abt the tensor we made
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0415, 0.4933, 0.3969, 0.6134],
        [0.7917, 0.4260, 0.8662, 0.9843],
        [0.4736, 0.1407, 0.3010, 0.7988]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

tensor operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [40]:
# Creating a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor = tensor + 10 # adds 10 to each element in the tensor
tensor

tensor([11, 12, 13])

In [41]:
# Multiply by 10
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [42]:
# divide by 10
tensor = tensor / 10
tensor

tensor([11., 12., 13.])

In [43]:
#subtract by 10
tensor = tensor - 10
tensor

tensor([1., 2., 3.])

In [45]:
## we could use built in functions
torch.mul(tensor,10)
torch.add(tensor,10)
torch.divide(tensor,10)
torch.subtract(tensor,10)

tensor([-9., -8., -7.])

### Matrix Multiplication

two main ways of performing multiplication in neural network and deep learning:
1. Element wise ---> each number multiplied by a number
2. Matrix Multiplication ---> performs dot product of 2 tensors (a.b)

2 is the most common found in deep learning

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [60]:
torch.rand(3,2) @ torch.rand(2,3) # note @ works same as matmul

tensor([[0.0406, 0.4947, 0.4024],
        [0.0085, 0.1215, 0.0799],
        [0.0512, 0.7823, 0.4652]])

In [52]:
# Element wise multiplication
tensor # [1,2,3]
print(f"{tensor} * {tensor} give us \n\n{tensor * tensor}")

tensor([1., 2., 3.]) * tensor([1., 2., 3.]) give us 

tensor([1., 4., 9.])


In [53]:
# Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14.)

In [54]:
# Matrix Multiplication by hand
1*1 + 2*2 + 3*3

14

In [56]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14.)
CPU times: user 4.64 ms, sys: 0 ns, total: 4.64 ms
Wall time: 4.39 ms


In [57]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 108 µs, sys: 10 µs, total: 118 µs
Wall time: 124 µs


tensor(14.)

We see significant time difference for even a small tensor, hence for advanced operations its better to use pytorch version rather than using for loops

### One of the most common errors in deep learning: Shape errors

In [62]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [63]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [65]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [68]:
# The matrix multiplication operations works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)